package-lock.json, package.json
Update to notification jobs to include new user invite
=> NSA-969 - Update notifications jobs package

azure/parameters.json, azure/template.json
=> Update ARM template

package-lock.json, package.json
To support formatting of override body using markdown
=> NSA-1666 - Update notifications to v2.8

package-lock.json, package.json
Updated notifications.jobs version
=> NSA-1723- help desk email

package-lock.json, package.json
Updated email content for SA reset password in notifications.jobs
=> Update notifications.jobs version

package-lock.json, package.json
updated notifications.jobs version
=> NSA-1753- unmigrated SA email

package-lock.json, package.json
changed link in notifications.jobs to new feedback survey on all required emails
=> NSA-1805 - updated notifications.jobs version

package-lock.json, package.json, src/app/monitor/index.js, src/infrastructure/config/schema.js, src/worker.js
* Live stop/start of processors
* Configurable concurrency
=> NSA-1984 - Processor management

package-lock.json, package.json
=> update packages based on reported vulns

package-lock.json, package.json
NSA-2401 Organisation Request Email link to Requests Page
=> NSA-2401 Organisation Request Email link to Requests Page

package-lock.json, package.json
=> NSA-2149 - improvements

package-lock.json, package.json
=> NSA-2150 - if org present

package-lock.json, package.json
=> NSA-2360-hanlderfix

package-lock.json, package.json
=> NSA-2360-url-correction

package-lock.json, package.json
Updated version for notification jobs to 5.3.5
=> NSA 2681 User Notification Of Changes

package-lock.json, package.json
=> NSA-2681 User Notification Of Changes

package-lock.json, package.json
dfe.service.notification.jobs component version has been updated
=> PR-NSA-4761-sql-orm-library-updated

package.json
Jira tickets:https://dfe-secureaccess.atlassian.net/browse/NSA-6015
https://dfe-secureaccess.atlassian.net/browse/NSA-6291
=> NSA-6015_invitation email template updated

package.json
Change email address from profile changes
=> Update notification.jobs version number 

package-lock.json, package.json
Jira ticket: 
https://dfe-secureaccess.atlassian.net/browse/NSA-6539
=> NSA-6539 - bumped version for login.dfe.notifications.jobs

package.json
update pre-release to test in dev
=> Feature/nsa 7109 sub service  approved email change

package.json
=> update json to pre-release v6.2.4

package-lock.json, package.json, src/infrastructure/config/schema.js
**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/DSI-7220
- bump `login.dfe.notification.jobs` version to include entra user registration email template when using feature flag active
- fix vulnerabilities using `npm audit fix`
- update config schema to include `enableEntraSignIn` feature flag
-  https://github.com/DFE-Digital/login.dfe.notifications.jobs/pull/177
- https://github.com/DFE-Digital/login.dfe.dsi-config/pull/16
=> [DSI-7220] Add Entra invitation email templates

src/infrastructure/config/schema.js
Mappings have been grouped by their folders in the GOV Notify interface.
=> Add all expected GOV Notify template mappings to config schema

src/handlers/notifications/invite/newUserInvitationV2.js, src/infrastructure/config/schema.js, test/handlers/notifications/invitationTests/newUserInvitationV2.withEntra.test.js, test/handlers/notifications/invitationTests/newUserInvitationV2.withoutEntra.test.js
**Jira ticket:** https://dfe-secureaccess.atlassian.net/browse/DSI-7362
- Replace`enableEntraSignIn` entra feature flag with `useEntraForAccountRegistration` to match the keyVault value 
https://github.com/DFE-Digital/login.dfe.dsi-config/pull/36
=> [DSI-7362] Replace `enableEntraSignIn` feature flag with `useEntraForAccountRegistration`
